kind: pipeline
type: docker
name: docker build

steps:
- name: build and push to private registry
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo:
      from_secret: repo
    registry:
      from_secret: registry
    purge: true
    compress: true
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    tags: latest
    custom_dns: 192.168.2.1

- name: build and push to docker hub
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: nope01/wowchat-docker
    purge: true
    compress: true
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    tags: latest

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: "{{#success build.status}}-----------------\n\n✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n✅ started: {{datetime build.started \"2006/01/02 15:04\" \"Europe/Berlin\"}}\n {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"Europe/Berlin\"}} {{/success}}\n"
  when:
    status:
    - success
    - failure
  depends_on:
    - build and push to private registry
    - build and push to docker hub
trigger:
  event:
  - cron
  cron:
  - build_monthly